import { MigrationInterface, QueryRunner } from "typeorm";

export class CreateTableProvincias1785355334444 implements MigrationInterface {

    public async up(queryRunner: QueryRunner): Promise<void> {
        queryRunner.query(`
            CREATE SEQUENCE IF NOT EXISTS public.provincias_id_seq
            START WITH 1
            INCREMENT BY 1
            NO MINVALUE
            NO MAXVALUE
            CACHE 1;

            CREATE TABLE public.provincias (
                id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                nome VARCHAR(100) NOT NULL UNIQUE,
                codigo VARCHAR(5) UNIQUE,
                created_at TIMESTAMP NOT NULL DEFAULT NOW(),
                updated_at TIMESTAMP NOT NULL DEFAULT NOW()
            );

            ALTER SEQUENCE public.provincias_id_seq
            OWNED BY public."provincias".id;
        `)
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        queryRunner.query(`
            DROP TABLE IF EXISTS public."provincias";

            DROP SEQUENCE IF EXISTS public.provincias_id_seq;
        `)
    }

}
