import { MigrationInterface, QueryRunner } from "typeorm";

export class CreateTableEnderecos1785355386314 implements MigrationInterface {

    public async up(queryRunner: QueryRunner): Promise<void> {
        queryRunner.query(`
            CREATE SEQUENCE IF NOT EXISTS public.enderecos_id_seq
            START WITH 1
            INCREMENT BY 1
            NO MINVALUE
            NO MAXVALUE
            CACHE 1;

            CREATE TABLE public.enderecos
            (
                id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                provincia_id INTEGER NOT NULL,
                municipio_id INTEGER NOT NULL,
                comuna VARCHAR(120),
                bairro VARCHAR(120),
                rua VARCHAR(200),
                numero VARCHAR(20),
                referencia VARCHAR(255),
                codigo_postal VARCHAR(20),
                latitude NUMERIC(10,7),
                longitude NUMERIC(10,7),
                created_at TIMESTAMP NOT NULL DEFAULT NOW(),
                updated_at TIMESTAMP NOT NULL DEFAULT NOW(),

                CONSTRAINT fk_endereco_provincia
                    FOREIGN KEY (provincia_id)
                    REFERENCES public.provincias(id),

                CONSTRAINT fk_endereco_municipio
                    FOREIGN KEY (municipio_id)
                    REFERENCES public.municipios(id)
            );

            ALTER SEQUENCE public.enderecos_id_seq
            OWNED BY public."enderecos".id;
        `)
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        queryRunner.query(``)
    }

}
