import { MigrationInterface, QueryRunner } from "typeorm";

export class CreateTableMunicipios1785355349840 implements MigrationInterface {

    public async up(queryRunner: QueryRunner): Promise<void> {
        queryRunner.query(`
            CREATE SEQUENCE IF NOT EXISTS public.municipios_id_seq
            START WITH 1
            INCREMENT BY 1
            NO MINVALUE
            NO MAXVALUE
            CACHE 1;

            CREATE TABLE public.municipios (
                id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                provincia_id INTEGER NOT NULL,
                nome VARCHAR(120) NOT NULL,

                created_at TIMESTAMP NOT NULL DEFAULT NOW(),
                updated_at TIMESTAMP NOT NULL DEFAULT NOW(),

                CONSTRAINT fk_municipio_provincia
                    FOREIGN KEY (provincia_id)
                    REFERENCES public.provincias(id)
                    ON DELETE RESTRICT,

                CONSTRAINT uq_municipio
                    UNIQUE (provincia_id, nome)
            );

            ALTER SEQUENCE public.municipios_id_seq
            OWNED BY public."municipios".id;

        `)
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        queryRunner.query(`
            DROP TABLE IF EXISTS public."municipios";

            DROP SEQUENCE IF EXISTS public.municipios_id_seq;
        `)
    }

}
